# spring
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fashion_class_book?useUnicode=true&characterEncoding=utf-8&serveTimezone=UTC
    username: root
    password: kndefems
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
  redis:
    database: 0
    host: 39.97.172.203
    port: 6379
    password:


# port
server:
  port: 8080

# 打印sql
logging:
  level:
    com.conan.fashionclassbook.mapper: debug

fdfs:
  so-timeout: 2500
  connect-timeout: 600
  thumb-image:
    width: 100
    height: 100
  tracker-list:
    - 39.97.172.203:22122
upload:
  base-url: http://39.97.172.203/
  allow-types:
    - image/jpeg
    - image/png
    - image/bmp
    - image/gif
    -


mybatis:
  typeAliasesPackage: com.conan.fashionclassbook.pojo
  mapperLocations: classpath:mappers/*Mapper.xml